//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DADS
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_sheets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public player_sheets()
        {
            this.games = new HashSet<games>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string spells { get; set; }
        public string notes { get; set; }
        public string inventory { get; set; }
        public string w1name { get; set; }
        public Nullable<int> w1damage { get; set; }
        public string w1description { get; set; }
        public string w1type { get; set; }
        public string w2name { get; set; }
        public Nullable<int> w2damage { get; set; }
        public string w2description { get; set; }
        public string w2type { get; set; }
        public string w3name { get; set; }
        public Nullable<int> w3damage { get; set; }
        public string w3description { get; set; }
        public string w3type { get; set; }
        public Nullable<int> exp { get; set; }
        public Nullable<int> cp { get; set; }
        public Nullable<int> sp { get; set; }
        public Nullable<int> gp { get; set; }
        public Nullable<int> pp { get; set; }
        public Nullable<int> profBonus { get; set; }
        public Nullable<int> insp { get; set; }
        public Nullable<int> stre { get; set; }
        public Nullable<int> dext { get; set; }
        public Nullable<int> cont { get; set; }
        public Nullable<int> inte { get; set; }
        public Nullable<int> wisd { get; set; }
        public Nullable<int> chari { get; set; }
        public Nullable<int> passWis { get; set; }
    
        public virtual users user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<games> games { get; set; }
    }
}
