//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DADS
{
    public class stats
    {
        public int cp { get; set; }
        public int sp { get; set; }
        public int gp { get; set; }
        public int pp { get; set; }
        public int exp { get; set; }

        public int proficiencyBonus { get; set; }

        public int strength { get; set; }
        public int dexterity { get; set; }
        public int constitution { get; set; }
        public int intelligence { get; set; }
        public int wisdom { get; set; }
        public int charisma { get; set; }
        public int passiveWisdom { get; set; }
    }
}