//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DADS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class users
    {
        public int Id { get; set; }
        [Required]
        public string username { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        [RegularExpression(@"^(.*){8,}$", ErrorMessage = "Password length must be at least 8 characters long.")]
        public string password { get; set; }
    
        public virtual games gameList { get; set; }
        public virtual player_sheets player_sheets { get; set; }
        public virtual games game { get; set; }
    }
}
